# Railway Configuration for Backend Service
[build]
builder = "dockerfile"
dockerfilePath = "backend/Dockerfile"
dockerContext = "backend"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "always"
